name: Node CI

on: [push, pull_request]

jobs:
  default:
    runs-on: ubuntu-latest
    env:
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
    steps:
      - uses: actions/checkout@v1
      - name: Get Node.js version
        id: node-version
        run: echo "::set-output name=version::$(cat .node-version)"
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: ${{ steps.node-version.version }}
      - name: Setup yarn
        run: |
          curl -o- -L https://yarnpkg.com/install.sh | bash
          export PATH="$HOME/.yarn/bin:$PATH"
      - name: Get yarn cache dir
        id: yarn-cache
        run: echo "::set-output name=dir::$(yarn cache dir)"
      - name: Cache
        uses: actions/cache@v1
        with:
          path: ${{ steps.yarn-cache.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - name: Install dependencies
        run: yarn --frozen-lockfile
      - name: Lint
        run: npm run lint
        env:
          CI: true
      - name: Build
        run: npm run build
        env:
          CI: true
      - name: Codecov
        run: npx codecov
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
      - name: Publish
        run: npm publish
        if: contains(github.ref, 'tags/v')
