name: Node CI

on: [push]

jobs:
  each-test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x, 13.x]

    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: install
        uses: sergioramos/yarn-actions/install@master
        with:
          frozen-lockfile: true
      - name: lint
        run: npm run lint
        env:
          CI: true
      - name: test
        run: npm run test
        env:
          CI: true
      - name: build
        run: npm run build
        env:
          CI: true
      - name: Codecov
        run: npx codecov
        if: startsWith(matrix.node-version, 12)
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
